"""
SHIELD AI — Shared constants.

All tuneable parameters live here so every module imports from one place.
To override for a specific deployment, set the corresponding env variable
(loaded via python-dotenv in main).
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Z-score anomaly scoring (zscore.py)
# ---------------------------------------------------------------------------

# NOTE: These are read by zscore.py to populate its CONFIG dict.
# Override via env vars to tune without touching code.

# Width of the trailing sliding window used to compute per-channel rolling stats.
WINDOW_SECONDS: int = int(os.getenv("WINDOW_SECONDS", "300"))  # 5 minutes

# Readings with |z-score| above this value are flagged as anomalous.
ZSCORE_THRESHOLD: float = float(os.getenv("ZSCORE_THRESHOLD", "3.0"))  # σ units

# Small floor added to rolling_std before division to prevent zero-division.
EPSILON: float = float(os.getenv("EPSILON", "1e-9"))

# ---------------------------------------------------------------------------
# Persistence filter (persistence.py)
# ---------------------------------------------------------------------------

# Number of consecutive anomalous readings required before emitting a confirmed alert.
PERSISTENCE_COUNT: int = int(os.getenv("PERSISTENCE_COUNT", "3"))

# ---------------------------------------------------------------------------
# Pathway I/O
# ---------------------------------------------------------------------------

# Directory that holds the single real CETP CSV (and any future CETP streams)
CETP_DATA_DIR: str = os.getenv("CETP_DATA_DIR", "data/cetp")

# Directory of simulated factory CSVs (generated by simulate_factories.py)
FACTORY_DATA_DIR: str = os.getenv("FACTORY_DATA_DIR", "data/factories")

# Alert evidence log (append-only JSONL)
ALERT_LOG_PATH: str = os.getenv("ALERT_LOG_PATH", "data/alerts/evidence_log.jsonl")

# v2 Anti-cheat tamper log (append-only JSONL)
TAMPER_LOG_PATH: str = os.getenv("TAMPER_LOG_PATH", "data/alerts/tamper_log.jsonl")

# ---------------------------------------------------------------------------
# Anomaly detection thresholds (tripwire.py)
# ---------------------------------------------------------------------------

# NOTE: COD_BASELINE is derived empirically from priya_cetp_i.csv (Feb 2026).
# The rolling mean of valid CETP inlet COD readings sits at ~193 mg/L.
COD_BASELINE: float = float(os.getenv("COD_BASELINE", "193.0"))  # mg/L

# NOTE: COD_THRESHOLD is intentionally set to 200 mg/L for the prototype demo.
# Real CETP data (priya_cetp_i.csv) has a max of 230.8 mg/L with 206 readings
# exceeding 200. In production, raise this to 450+ mg/L based on regulatory limits.
COD_THRESHOLD: float = float(os.getenv("COD_THRESHOLD", "200.0"))  # mg/L

# ---------------------------------------------------------------------------
# Temporal backtracking (backtrack.py)
# ---------------------------------------------------------------------------

# NOTE: PIPE_TRAVEL_MINUTES is a FIXED CONSTANT for v1.
# In v2 this will be replaced by a dynamic, pipe-length-aware calculation
# derived from GIS network data and real-time flow-rate sensors.
# Do NOT remove this constant — it is the single source of truth for the
# temporal offset used in the asof_join attribution logic.
PIPE_TRAVEL_MINUTES: int = int(os.getenv("PIPE_TRAVEL_MINUTES", "15"))

# Tolerance window for asof_join (seconds either side of T_backtrack)
ASOF_TOLERANCE_SECONDS: int = int(os.getenv("ASOF_TOLERANCE_SECONDS", "120"))  # ±2 min

# ---------------------------------------------------------------------------
# v2 Anti-cheat thresholds (anti_cheat.py)
# ---------------------------------------------------------------------------

# Zero-variance: flag DIGITALLY_TAMPERED if stddev == 0 for this many minutes
ZERO_VARIANCE_MINUTES: int = int(os.getenv("ZERO_VARIANCE_MINUTES", "5"))

# Chemical fingerprint: flag PHYSICAL_TAMPERING if COD drops by this fraction
# while TSS stays within TSS_STABLE_FRACTION of its prior value
COD_DROP_FRACTION: float = float(os.getenv("COD_DROP_FRACTION", "0.80"))
TSS_STABLE_FRACTION: float = float(os.getenv("TSS_STABLE_FRACTION", "0.20"))

# Minimum blackout window length to trigger guilt-by-disconnection alarm (minutes)
BLACKOUT_MIN_MINUTES: int = int(os.getenv("BLACKOUT_MIN_MINUTES", "10"))

# ---------------------------------------------------------------------------
# Integrations
# ---------------------------------------------------------------------------

# Webhook URL for alert forwarding (leave blank to disable)
SHIELD_WEBHOOK_URL: str = os.getenv("SHIELD_WEBHOOK_URL", "")
